### ISSUE TITLE
Definition of Metadata Quality KPIs

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmcp#2] opened 2019-04-11 11:05 UTC
- Drivers: WIS GUI, WIS2, Usability, Discovery, need to handle granularity, OSCAR to WIS, etc
- Scope: identifying quality KPIs - how, priorities, etc
- Initial sources for defining the KPIs (WMCP 1.3, guidance documentation, WMO Wiki, NOAA Schematron, ...)

**Comment by gaubert** [comment] 2019-04-11 15:42
Quickly talking with Kate at the end of the meeting, we thought it would make sense to define groups of KPI. See below some of the categories. Please feel free to add additional ones.

1. **Minimum set of elements/information to added in the Metadata**
      - Specific keywords for categorising the product (define a thematic/taxonomy)      


2. **Editorial content improvement**
      - Title Mandatory information
      - Abstract Mandatory Information (product focused information, data services links ?)

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:12
2.a)  Currently : guidance asks for the bulletin code to be present.  
Titles should be consistent, and contain meaningful and useful (from a search / discovery perspective) content.
Can we develop some preferred wording (that is more specific and more meaningful) for each "type" of bulletin?
And, for these bulletin titles, should they include a term that signifies that they are basically a 'granule-level' record?
Also (assuming that we want each bulletin's record to be consistent, in design, with all others of the same type, and to be consistent with a related  "umbrella" / collection-level record (to manage hierarchies of metadata) .. can we draft what that umbrella record's title might be ?  (eg will it include the word 'collection')

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:27
1.  Station identifiers : where, what, and how.  
Old guidance  (WMCP 1.2) recommended that these be added as keywords, with a keywordTypeCode of 'place';  As well, some example/template metadata records included station names in the abstract.  Looking at implementation practice, some records do both, some do neither, and some also include in the abstract (as well as the station name) the station numbers.
In the latest GUIDE, adoption of the new station number has been recommended.  We need to get confirmation from WMO that that recommendation still holds.
?Should we include both the old and new station number?
?Is the OSCAR linking to the WIS still going to be via linking to DWD?  (We need to understand where OSCAR will be linking to, and to then ensure that whatever OSCAR search is needed can be fulfilled by our recommendation).
Should the station number in a metadata record also have the capacity to link to OSCAR?  (if so, this might need to be implemented as an <xlink/>, rather than a <characterString/> )

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:29
whoops, it didn't accept left and right brackets ( /< and />).  The last sentence above should read "..might need to be implemented as an xlink, rather than as a characterString"

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:36
For bulletins metadata, can we develop some words which indicate that the data available via the WIS is ephemeral  ("available for 24 hours only" or similar)?
(Also: do we know where that data is available more longterm?  And can we start to log these, with a view to exploring the feasibility of the bulletin records indicating where that same data is retained and available for a longer time?)

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:37
For WMOEssential data, is it possible for us to ask each distributor to provide an explicit link to the data  (which doesn't require a login)?

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:45
1.  Temporal Extent, for bulletins, shouldn't show a date range.  They (?always?  There might be exceptions ...) should perhaps instead say "now" (rather than '2010' to 'now'), with a comment explaining in words.  
For instance, the CLIMAT report metadata (if it still existed) could say, in the date fields: 'now' and 'now; and in the comments section:  "Latest completed month".

**Comment by katerobertsfreeman** [comment] 2019-05-09 16:52
Where feasible, data parameter terms should be included.  Some may need to be generalized for searching;  But the more detailed data dictionary (especially for non-bulletin metadata) should also always be linked to, from the metadata record.

(?Are all bulletin data parameters already included in the WMO Codes Registry?  
If so, is it feasible to for these to be used as dataParam keywords?  
?Do we need to develop ( or create a subset from elsewhere), a controlled list of data parameter terms to be searched on .. for both bulletin and non-bulleting metadata?

**Comment by gaubert** [comment] 2019-05-14 08:37
@katerobertsfreeman **Station Information in the Metadata** When talking about the station ID to clarify things, are you talking about the WIGOS identifier ? It is possible to link the Station information in the WMCP with the OSCAR information. For instance the information for the Aachen station in Germany is available here: https://oscar.wmo.int/surface//index.html#/search/station/stationReportDetails/2890
The WIGOS ID is 0-20000-0-10505 and also available from that page. As you said this link can be added in the metadata as an xlink. Using the API it might even be possible to create a url using the WIGOS ID. I do not know very well the station API and that would need to be studied.
Regarding 2.a Bulletin ID o be present, does it have to be in the title ?

**Bulletin information**
Regarding your bulletin templating with the ephemeral information, this is a good idea, we should add some sentences to be added at the end of the abstract.
Regarding your question concerning where the data is kept for a longer term, it is the case for satellite observations circulated on the WIS. For instance we keep all our observations in the archive, the issue is that they will not be kept as bulletins but more as observations in another format.

**WMO Essential Data**
Ok we can check that there is an onlineResource. It cannot always be a direct link to the data files as sometimes you might have to register to access the data (If it isn't available over internet but from another distribution mean).

** Temporal Extent **
The temporal extent range should be present and can be check to always have a begin date and an end date or a 'now'
I do not understand the CLIMAT report issue. Isn't it the same issue with the temporal extent ? The climate records are covering a time period from to an end. For us they are created through re-processing campaigns so it always a well specified time range (from 2008-01-01 end 2018-12-31).

** Abstract **
As you said Kate we can provide some guidance on the abstract structure such that it contains some information (type of product/bulletin, parameter, format). It is difficult to have an automated tool verifying that KPI maybe others have ideas ?

One thing we should be is to flag all the bulletin metadata records that contain the initial template used to generate the metadata records in 2012:

> IEDX01 BUFR bulletin available from EUMP (EUMETSAT - DARMSTADT)
>--
>Satellite Centre EUMETSAT Darmstadt - EUMETSAT
>---- The bulletin is coded as BUFR code form: FM 94 (BUFR, Binary universal form for the >representation of meteorological data) .   (Refer to WMO No.306 - Manual on Codes for the >definition of WMO international codes)  ---- The IEDX01 TTAAii Data Designators decode (2) as: T1 >(I): Observational data (Binary coded) - BUFR. A2 (X): Global Area (area not definable).  (2: Refer to >WMO No.386 - Manual on the GTS - Attachment II.5)  ---- WMO No.9 - Volume C1 'Remarks' field: >IASI SOUNDING (TEMP AND HUMIDITY) GLOBAL DATA`
  
** Meteorological Parameter **

Yes I agree with you, we can add a keyword with the meteo param information.

**Comment by katerobertsfreeman** [comment] 2019-05-14 10:27
Station identifiers:
@Guillaume : we agree.  The questions are which link we recommend, and whether xlink is acceptable to use.  
Re "which link": 
 in the "WIS GUIDE" rev.2017, section 5 [available from http://wis.wmo.int/file=3720 or https://wis.wmo.int/WIS-Guide ],  the recommended expression, in the keyword field is:
    <gmd:keyword>
      <gco:CharacterString>0-20000-0-94287; CAIRNS AERO [ http://data.wmo.int/wigosid=0-20000-0-94287 ]</gco:CharacterString>
    </gmd:keyword>
That url format [ http://data.wmo.int/wigosid=0-20000-0-10505 ] is what Dave Thomas or Steve Foreman recommended.  
Its a re-direct to 
https://oscar.wmo.int/surface//index.html#/search/station/stationReportDetails/0-20000-0-10505
  and the content at the above url seems to be the same as the content available from the url that you have just mentioned ...( e.g. to https://oscar.wmo.int/surface//index.html#/search/station/stationReportDetails/2890  ).

**Comment by katerobertsfreeman** [comment] 2019-05-14 11:11
Data Parameter as keyword 
@guillaume : we're agreed about the general approach.  Some specifics that need to be teased out might be:
a) we need guidance on which one (if more than one) in the codes registry to use.  For instance: if we want to add a keyword term (of KeywordTypeCode 'dataParam'), for "dewpoint temperature" ... at this url, there seems to be at least 4 that one might use " http://codes.wmo.int/ui/text-search?query=dewpoint   Three of the 4 are for kelvin units, and 1 of the 4 is for celsius.

b) we need to determine whether the GISCS can handle xlinks [again];

c) Assuming that we took a conservative path of no xlink, and that the correct url for dewpoint temp were : http://codes.wmo.int/bufr4/b/12/_003
then, should our current guidance (in section 5 of the WIS GUIDE at  https://wis.wmo.int/WIS-Guide ] change from: 
<gmd:keyword>
<gco:CharacterString>Dewpoint temperature</gco:CharacterString>
</gmd:keyword>

? to ?
<gmd:keyword>
<gco:CharacterString>Dewpoint temperature [ http://codes.wmo.int/bufr4/b/12/_003 ] </gco:CharacterString>
</gmd:keyword>

**Comment by gaubert** [comment] 2019-05-14 12:53
@katerobertsfreeman can you provide an example with an xlink to let the group see if there are some issues with it. From my point of view it is fine.
Your data parameter proposal looks fine with me. Same we need to understand what are the issues with the xlink ? From my point of view xlink or non-xlink solution both have to be interpreted by the GISC and catalogue to create a link for the user: in the end that should be the goal.

**Comment by amilan17** [comment] 2019-05-16 11:16
**NOAA Title Guidance (draft)**
Style Guidelines

- A good archival title summarizes what, where and when data were collected so that a data consumer can read the title and make an informed decision about learning more about the data. 
- Capitalize all major words (nouns, pronouns, verbs, adjectives, adverbs, and some conjunctions).
- Avoid using acronyms unless defined in the abstract, especially for projects or organizations. Exception applies to “NOAA” as our audience is familiar with our acronym.
- If you include an acronym, spell out the meaning of the acronym then put the acronym in parentheses after the meaning. Do not assume that everyone reading the title will know or understand all acronyms or jargon. Some common acronyms may be widely understood within a specific domain. 
- Always, spell out the title acronym at least once in the abstract text.

**Comment by gaubert** [comment] 2019-05-20 07:01
As discussed during the last Teclo we have regrouped all the points discussed in this issue thread in a document available from Github: [KPIs](https://github.com/wmo-im/wmcp/blob/master/Meetings/WMCP%20Metadata%20Quality%20KPIs%20definition.docx )

I propose the following to add comments in the document: 
- Make sure you have the latest committed version from Github.
- Use the "track changes" to insert your comments
- Then update the new version in Github and insert a comment in that issue thread with a link to the updated document.

Thanks a lot

**Comment by efucile** [comment] 2019-05-21 12:35
Document on KPIs moved here https://github.com/wmo-im/wmcp-docs/blob/master/Meetings/WMCP-metadata-quality-KPI.md

**Comment by gaubert** [comment] 2019-05-23 12:23
Hi all,
I am at the DWD GISC workshop and David Thomas mentioned that there is no guidance for adding the keywords  "global Exchange, regional Exchange, ...". The data with the globalExchange keyword should be cached by the different GISCs and made available. We should check if this is true and then if not them recommend to have it added in the guidance documentation and regulation.
Any thoughts about that point ?

**Comment by gaubert** [comment] 2019-08-27 07:26
@efucile @katerobertsfreeman @amilan17 here is a quick reference to to edit adoc documents on github:
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

**Closed** 2019-08-29 12:48 UTC
